version: "3.9"
services:
    nginx:
        image: hacker-strategies_nginx:latest
        build:
            context: ./frontend
        ports: 
            - "443:443"
            - "80:80"
        secrets:
            - hs_ssl_cert
            - hs_ssl_key
        networks:
            - hs-net
    api:
        image: hacker-strategies_api:latest
        build:
            context: ./api
        networks:
            - hs-net
networks:
    hs-net:
        driver: overlay

secrets:
    hs_ssl_cert:
        external: true
    hs_ssl_key:
        external: true

